package com.dmi.util.action

enum class TouchZone1D { FIRST, MIDDLE1, MIDDLE2, LAST }

enum class TouchZone {
    TOP_LEFT, TOP_MIDDLE1, TOP_MIDDLE2, TOP_RIGHT,
    MIDDLE1_LEFT, MIDDLE1_MIDDLE1, MIDDLE1_MIDDLE2, MIDDLE1_RIGHT,
    MIDDLE2_LEFT, MIDDLE2_MIDDLE1, MIDDLE2_MIDDLE2, MIDDLE2_RIGHT,
    BOTTOM_LEFT, BOTTOM_MIDDLE1, BOTTOM_MIDDLE2, BOTTOM_RIGHT
}