package com.dmi.perfectreader.manualtest.testbook;

@SuppressWarnings("unused")
public abstract class TestBooks {
    public static final String CARROLL_ALICE_IN_WONDERLAND = "assets://manualtest/testBooks/carrollAliceInWonderland.epub";
    public static final String TOLKIEN_LORD_OF_THE_RINGS = "assets://manualtest/testBooks/tolkienLordOfTheRings.epub";
    public static final String LUKIANENKO_NEW_DOZOR = "assets://manualtest/testBooks/lukianenkoNewDozor.epub";
    public static final String PRATCHETT_INTERESTING_TIMES = "assets://manualtest/testBooks/pratchettInterestingTimes.epub";
    public static final String PRATCHETT_MEN_AT_ARMS = "assets://manualtest/testBooks/pratchettMenAtArms.epub";

    public static abstract class Extracted {
        public static final String[] CARROLL_ALICE_IN_WONDERLAND = new String[] {
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/wrap0000.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-0.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-1.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-2.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-3.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-4.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-5.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-6.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-7.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-8.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-9.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-10.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-11.htm.html",
                "assets://manualtest/testBooks/extracted/carrollAliceInWonderland/@public@vhost@g@gutenberg@html@files@28885@28885-h@28885-h-12.htm.html"
        };

        public static final String[] LORD_OF_THE_RINGS = new String[] {
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/cover.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/title.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section1.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section2.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section3.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section4.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section5.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section6.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section7.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section8.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section9.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section10.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section11.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section12.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section13.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section14.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section15.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section16.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section17.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section18.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section19.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section20.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section21.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section22.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section23.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section24.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section25.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section26.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section27.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section28.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section29.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section30.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section31.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section32.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section33.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section34.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section35.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section36.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section37.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section38.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section39.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section40.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section41.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section42.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section43.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section44.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section45.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section46.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section47.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section48.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section49.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section51.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section52.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section53.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section54.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section55.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section56.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section57.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section58.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section59.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section60.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section61.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section62.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section63.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section64.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section65.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section66.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section67.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section68.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section69.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section70.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section71.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section72.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section73.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section74.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section75.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section76.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section77.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section78.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section79.xhtml",
                "assets://manualtest/testBooks/extracted/tolkienLordOfTheRings/section80.xhtml",
        };
    }
}
