CREATE TABLE BookLocation(uri TEXT PRIMARY KEY NOT NULL, offset REAL NOT NULL);
CREATE TABLE LastBook(id INTEGER PRIMARY KEY NOT NULL, uri TEXT NOT NULL);
CREATE TABLE Setting(key TEXT PRIMARY KEY NOT NULL, intValue INTEGER, realValue REAL, textValue TEXT);