LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE:= libicu
LOCAL_SRC_FILES:= \
    ../repo/icu/source/common/errorcode.cpp \
    ../repo/icu/source/common/putil.cpp \
    ../repo/icu/source/common/umath.c \
    ../repo/icu/source/common/utypes.c \
    ../repo/icu/source/common/uinvchar.c \
    ../repo/icu/source/common/umutex.cpp \
    ../repo/icu/source/common/ucln_cmn.c \
    ../repo/icu/source/common/uinit.cpp \
    ../repo/icu/source/common/uobject.cpp \
    ../repo/icu/source/common/cmemory.c \
    ../repo/icu/source/common/charstr.cpp \
    ../repo/icu/source/common/udata.cpp \
    ../repo/icu/source/common/ucmndata.c \
    ../repo/icu/source/common/udatamem.c \
    ../repo/icu/source/common/umapfile.c \
    ../repo/icu/source/common/udataswp.c \
    ../repo/icu/source/common/ucol_swp.cpp \
    ../repo/icu/source/common/utrace.c \
    ../repo/icu/source/common/uhash.c \
    ../repo/icu/source/common/uhash_us.cpp \
    ../repo/icu/source/common/uenum.c \
    ../repo/icu/source/common/ustrenum.cpp \
    ../repo/icu/source/common/uvector.cpp \
    ../repo/icu/source/common/ustack.cpp \
    ../repo/icu/source/common/uvectr32.cpp \
    ../repo/icu/source/common/uvectr64.cpp \
    ../repo/icu/source/common/ucnv.c \
    ../repo/icu/source/common/ucnv_bld.cpp \
    ../repo/icu/source/common/ucnv_cnv.c \
    ../repo/icu/source/common/ucnv_io.cpp \
    ../repo/icu/source/common/ucnv_cb.c \
    ../repo/icu/source/common/ucnv_err.c \
    ../repo/icu/source/common/ucnvlat1.c \
    ../repo/icu/source/common/ucnv_u7.c \
    ../repo/icu/source/common/ucnv_u8.c \
    ../repo/icu/source/common/ucnv_u16.c \
    ../repo/icu/source/common/ucnv_u32.c \
    ../repo/icu/source/common/ucnvscsu.c \
    ../repo/icu/source/common/ucnvbocu.cpp \
    ../repo/icu/source/common/ucnv_ext.cpp \
    ../repo/icu/source/common/ucnvmbcs.c \
    ../repo/icu/source/common/ucnv2022.cpp \
    ../repo/icu/source/common/ucnvhz.c \
    ../repo/icu/source/common/ucnv_lmb.c \
    ../repo/icu/source/common/ucnvisci.c \
    ../repo/icu/source/common/ucnvdisp.c \
    ../repo/icu/source/common/ucnv_set.c \
    ../repo/icu/source/common/ucnv_ct.c \
    ../repo/icu/source/common/uresbund.cpp \
    ../repo/icu/source/common/ures_cnv.c \
    ../repo/icu/source/common/uresdata.c \
    ../repo/icu/source/common/resbund.cpp \
    ../repo/icu/source/common/resbund_cnv.cpp \
    ../repo/icu/source/common/messagepattern.cpp \
    ../repo/icu/source/common/ucat.c \
    ../repo/icu/source/common/locmap.c \
    ../repo/icu/source/common/uloc.cpp \
    ../repo/icu/source/common/locid.cpp \
    ../repo/icu/source/common/locutil.cpp \
    ../repo/icu/source/common/locavailable.cpp \
    ../repo/icu/source/common/locdispnames.cpp \
    ../repo/icu/source/common/loclikely.cpp \
    ../repo/icu/source/common/locresdata.cpp \
    ../repo/icu/source/common/bytestream.cpp \
    ../repo/icu/source/common/stringpiece.cpp \
    ../repo/icu/source/common/stringtriebuilder.cpp \
    ../repo/icu/source/common/bytestriebuilder.cpp \
    ../repo/icu/source/common/bytestrie.cpp \
    ../repo/icu/source/common/bytestrieiterator.cpp \
    ../repo/icu/source/common/ucharstrie.cpp \
    ../repo/icu/source/common/ucharstriebuilder.cpp \
    ../repo/icu/source/common/ucharstrieiterator.cpp \
    ../repo/icu/source/common/dictionarydata.cpp \
    ../repo/icu/source/common/appendable.cpp \
    ../repo/icu/source/common/ustr_cnv.c \
    ../repo/icu/source/common/unistr_cnv.cpp \
    ../repo/icu/source/common/unistr.cpp \
    ../repo/icu/source/common/unistr_case.cpp \
    ../repo/icu/source/common/unistr_props.cpp \
    ../repo/icu/source/common/utf_impl.c \
    ../repo/icu/source/common/ustring.cpp \
    ../repo/icu/source/common/ustrcase.cpp \
    ../repo/icu/source/common/ucasemap.cpp \
    ../repo/icu/source/common/ucasemap_titlecase_brkiter.cpp \
    ../repo/icu/source/common/cstring.c \
    ../repo/icu/source/common/ustrfmt.c \
    ../repo/icu/source/common/ustrtrns.cpp \
    ../repo/icu/source/common/ustr_wcs.cpp \
    ../repo/icu/source/common/utext.cpp \
    ../repo/icu/source/common/unistr_case_locale.cpp \
    ../repo/icu/source/common/ustrcase_locale.cpp \
    ../repo/icu/source/common/unistr_titlecase_brkiter.cpp \
    ../repo/icu/source/common/ustr_titlecase_brkiter.cpp \
    ../repo/icu/source/common/normalizer2impl.cpp \
    ../repo/icu/source/common/normalizer2.cpp \
    ../repo/icu/source/common/filterednormalizer2.cpp \
    ../repo/icu/source/common/normlzr.cpp \
    ../repo/icu/source/common/unorm.cpp \
    ../repo/icu/source/common/unormcmp.cpp \
    ../repo/icu/source/common/chariter.cpp \
    ../repo/icu/source/common/schriter.cpp \
    ../repo/icu/source/common/uchriter.cpp \
    ../repo/icu/source/common/uiter.cpp \
    ../repo/icu/source/common/patternprops.cpp \
    ../repo/icu/source/common/uchar.c \
    ../repo/icu/source/common/uprops.cpp \
    ../repo/icu/source/common/ucase.cpp \
    ../repo/icu/source/common/propname.cpp \
    ../repo/icu/source/common/ubidi_props.c \
    ../repo/icu/source/common/ubidi.c \
    ../repo/icu/source/common/ubidiwrt.c \
    ../repo/icu/source/common/ubidiln.c \
    ../repo/icu/source/common/ushape.cpp \
    ../repo/icu/source/common/uscript.c \
    ../repo/icu/source/common/uscript_props.cpp \
    ../repo/icu/source/common/usc_impl.c \
    ../repo/icu/source/common/unames.cpp \
    ../repo/icu/source/common/utrie.cpp \
    ../repo/icu/source/common/utrie2.cpp \
    ../repo/icu/source/common/utrie2_builder.cpp \
    ../repo/icu/source/common/bmpset.cpp \
    ../repo/icu/source/common/unisetspan.cpp \
    ../repo/icu/source/common/uset_props.cpp \
    ../repo/icu/source/common/uniset_props.cpp \
    ../repo/icu/source/common/uniset_closure.cpp \
    ../repo/icu/source/common/uset.cpp \
    ../repo/icu/source/common/uniset.cpp \
    ../repo/icu/source/common/usetiter.cpp \
    ../repo/icu/source/common/ruleiter.cpp \
    ../repo/icu/source/common/caniter.cpp \
    ../repo/icu/source/common/unifilt.cpp \
    ../repo/icu/source/common/unifunct.cpp \
    ../repo/icu/source/common/uarrsort.c \
    ../repo/icu/source/common/brkiter.cpp \
    ../repo/icu/source/common/ubrk.cpp \
    ../repo/icu/source/common/brkeng.cpp \
    ../repo/icu/source/common/dictbe.cpp \
    ../repo/icu/source/common/rbbi.cpp \
    ../repo/icu/source/common/rbbidata.cpp \
    ../repo/icu/source/common/rbbinode.cpp \
    ../repo/icu/source/common/rbbirb.cpp \
    ../repo/icu/source/common/rbbiscan.cpp \
    ../repo/icu/source/common/rbbisetb.cpp \
    ../repo/icu/source/common/rbbistbl.cpp \
    ../repo/icu/source/common/rbbitblb.cpp \
    ../repo/icu/source/common/serv.cpp \
    ../repo/icu/source/common/servnotf.cpp \
    ../repo/icu/source/common/servls.cpp \
    ../repo/icu/source/common/servlk.cpp \
    ../repo/icu/source/common/servlkf.cpp \
    ../repo/icu/source/common/servrbf.cpp \
    ../repo/icu/source/common/servslkf.cpp \
    ../repo/icu/source/common/uidna.cpp \
    ../repo/icu/source/common/usprep.cpp \
    ../repo/icu/source/common/uts46.cpp \
    ../repo/icu/source/common/punycode.cpp \
    ../repo/icu/source/common/util.cpp \
    ../repo/icu/source/common/util_props.cpp \
    ../repo/icu/source/common/parsepos.cpp \
    ../repo/icu/source/common/locbased.cpp \
    ../repo/icu/source/common/cwchar.c \
    ../repo/icu/source/common/wintz.c \
    ../repo/icu/source/common/dtintrv.cpp \
    ../repo/icu/source/common/ucnvsel.cpp \
    ../repo/icu/source/common/propsvec.c \
    ../repo/icu/source/common/ulist.c \
    ../repo/icu/source/common/uloc_tag.c \
    ../repo/icu/source/common/icudataver.c \
    ../repo/icu/source/common/icuplug.c \
    ../repo/icu/source/common/listformatter.cpp \
    ../repo/icu/source/common/lrucache.cpp \
    ../repo/icu/source/common/sharedobject.cpp \
    ../repo/icu/source/common/simplepatternformatter.cpp \
    ../repo/icu/source/stubdata/stubdata.c \
    $(NULL)
LOCAL_C_INCLUDES += \
    $(LOCAL_PATH)/../repo/icu/source/common \
    $(NULL)
LOCAL_EXPORT_C_INCLUDES += \
    $(LOCAL_PATH)/../repo/icu/source/common \
    $(NULL)
LOCAL_ARM_MODE := arm
LOCAL_CFLAGS += -O2 -DU_COMMON_IMPLEMENTATION
include $(BUILD_SHARED_LIBRARY)
